spring:
  metrics:
    export:
      enabled: false
  main:
    banner-mode: 'off'
camelsvc:
  sleepSecOrigin: 1
  sleepSecBound: 4
mockservice:
  server.port: 9000
server:
  tomcat:
    ajp-port: 8081
    enable-apr: true
  port: 8080
camel:
  springboot:
    name: CamelRestMockService
endpoints:
  enabled: true
  health:
    enabled: true
  metrics:
    filter:
      enabled: false
    enabled: false
 