---
- name: Installing required software
  hosts: app_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes
  become_user: root
  roles:
    - geerlingguy.java
    - bertvv.httpd
    - springboot-role

# httpd extra tasks
- name: Opening Firewall ports
  hosts: app_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes
  become_user: root
  tasks:
     - systemd:
          name: firewalld
          enabled: yes
          state: started

     - firewalld:
        port: 12348-12349/tcp 
        permanent: true
        state: enabled
        zone: public

     - firewalld:
        service: http
        permanent: true
        state: enabled
        zone: public

     - firewalld:
        service: https
        permanent: true
        state: enabled
        zone: public

     - service:
          name: firewalld
          state: reloaded

- name: Configuring Reverse Proxy to Camel Svc
  hosts: app_server
  remote_user: "{{ ansible_ssh_user | default('vagrant') }}"
  become: yes
  tasks:
     - package:
          name: libselinux-python
          state: present
     - package:
          name: libsemanage-python
          state: present
     # https://confluence.atlassian.com/bitbucketserverkb/permission-denied-in-apache-logs-when-used-as-a-reverse-proxy-790957647.html
     - seboolean:
          name: httpd_can_network_connect
          state: yes
          persistent: yes
          
     - template: 
          src: camelsvc.conf.j2 
          dest: "{{ httpd_config_dir }}/camelsvc.conf"
          owner: root
          group: root
          setype: httpd_config_t
          mode: '0644'

     - service:
          name: httpd
          state: restarted