---
- name: Installing Tomcat APR
  hosts: app_server_tuned
  remote_user: '{{ ansible_ssh_user | default(''vagrant'') }}'
  become: true
  become_user: root
  tasks:
    - package:
        name: openssl-devel
        state: present
    - package:
        name: apr-devel
        state: present
    - package:
        name: gcc
        state: present
# check if not installed
# discover parameters
# configure
# install
# https://github.com/ricardozanini/ansible-role-apr/blob/master/tasks/main.yml
# http://tomcat.apache.org/native-doc/

- name: Copy tuned properties
  hosts: app_server_tuned
  remote_user: '{{ ansible_ssh_user | default(''vagrant'') }}'
  become: true
  become_user: root
  tasks:
    - file:
        path: '/home/{{ spring_boot_application_id }}'
        state: directory
        mode: '0755'
    - template:
        src: tuned-application.yml.j2
        dest: '{{ spring_boot_user_dir }}/application.yml'
        owner: '{{ spring_boot_application_id }}'
        group: '{{ spring_boot_application_id }}' 
        mode: '0644'
        force: yes
    - copy:
        src: async-logback.xml
        dest: '{{ spring_boot_user_dir }}/logback.xml'
        mode: '0644'
        owner: '{{ spring_boot_application_id }}'
        group: '{{ spring_boot_application_id }}'
        force: yes
    - copy:
        src: 00-mpm.conf
        dest: '/etc/httpd/conf.modules.d'
        owner: root
        group: root
        setype: httpd_config_t
        mode: '0644'
    - template:
        src: tuned-camelsvc.conf.j2
        dest: '{{ httpd_config_dir }}/camelsvc.conf'
        owner: root
        group: root
        setype: httpd_config_t
        mode: '0644'
    - service:
        name: httpd
        state: restarted
    - service:
        name: '{{ spring_boot_application_id }}.service'
        state: restarted
